# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    default_filter_set_settings:
        format: webp
    filter_sets:
        miniature:
            quality: 75
            filters:
                thumbnail: { size: [200, 250], mode: outbound }
        mini_miniature:
            quality: 75
            filters:
                thumbnail: { size: [140, 175], mode: outbound }
        adv_banner:
            quality: 75
            filters:
                thumbnail: { size: [1296, 250], mode: outbound }
