vich_uploader:
    db_driver: orm

    mappings:
        platforms:
            uri_prefix: "%platform_images%"
            upload_destination: "%kernel.project_dir%/public%platform_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        advertisings:
            uri_prefix: "%adv_images%"
            upload_destination: "%kernel.project_dir%/public%adv_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
